### ISSUE TITLE
Version for Linux?

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [Squiblydoo/ModBringer#2]
I'm a Linux user, and also a steam deck user, and would love a build for Linux.

**Comment by Squiblydoo** [comment]
I can look into it. It should not be hard to do. ModBringer's main function is moving some files around. 
However, I do not have a Steam Deck, to test on. I will likely need to rely on you to confirm if it works also on Steam Deck (which I think it would if I can implement it for Linux). 

I'll look into it in the next few days and test it on my own system.

**Comment by Squiblydoo** [comment]
@LovecraftianGodsKiller Please follow this link and try it out: https://github.com/Squiblydoo/ModBringer/releases/tag/1.2.3 
I tested it works as expected on my Linux system. I don't have a steam deck to test on there.

**On Linux, you have to launch it from a terminal.** 

Open the **terminal** application, navigate to the download directory using the command `cd` (so for example `cd ~/Downloads/Linux_modbringer/`) then execute it with `.\modbringer`. It will then give you directions for setup.

(You may also be able to unzip it, then rightclick the directory and choose `Open in Terminal`).

I had never created a more advanced GUI and developing a new one is beyond the scope of the time I have for this project. :(

**Comment by Squiblydoo** [comment]
I have not heard back, but from my perspective, a Linux version now exists. If you identify any issues with it at a later time, please feel free to open a new issue.
